config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :beginners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'beginners#index'
  root to: "beginners#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beginner.rb
class Beginner < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :element, :author, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :beginner, dependent: :destroy
  validates :text, :author, :beginner, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :beginners
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/beginners_controller.rb
class BeginnersController < ApplicationController
  before_action :set_beginner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /beginners
  # GET /beginners.json
  def index
    @beginners = Beginner.all
  end

  # GET /beginners/1
  # GET /beginners/1.json
  def show
    @new_comment = @beginner.comments.new
  end

  # GET /beginners/new
  def new
    @beginner = current_user.beginners.new
  end

  # GET /beginners/1/edit
  def edit
  end

  # POST /beginners
  # POST /beginners.json
  def create
    @beginner = current_user.beginners.new(beginner_params)

    respond_to do |format|
      if @beginner.save
        format.html { redirect_to @beginner, notice: 'Beginner was successfully created.' }
        format.json { render :show, status: :created, location: @beginner }
      else
        format.html { render :new }
        format.json { render json: @beginner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beginners/1
  # PATCH/PUT /beginners/1.json
  def update
    respond_to do |format|
      if @beginner.update(beginner_params)
        format.html { redirect_to @beginner, notice: 'Beginner was successfully updated.' }
        format.json { render :show, status: :ok, location: @beginner }
      else
        format.html { render :edit }
        format.json { render json: @beginner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beginners/1
  # DELETE /beginners/1.json
  def destroy
    @beginner.destroy
    respond_to do |format|
      format.html { redirect_to beginners_url, notice: 'Beginner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beginner
      @beginner = Beginner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beginner_params
      params.require(:beginner).permit(:title, :element, :author)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :author, :beginner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beginners_helper.rb
module BeginnersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/beginners/_form.html.erb
<%= form_with(model: beginner, local: true) do |form| %>
  <% if beginner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beginner.errors.count, "error") %> prohibited this beginner from being saved:</h2>

      <ul>
      <% beginner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :element %>
    <%= form.text_area :element %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beginners/edit.html.erb
<h1>Editing Beginner</h1>

<%= render 'form', beginner: @beginner %>

<%= link_to 'Show', @beginner %> |
<%= link_to 'Back', beginners_path %>

app/views/beginners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beginners</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Element</th>
      <th>Author</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beginners.each do |beginner| %>
      <tr>
        <td><%= beginner.title %></td>
        <td><%= beginner.element %></td>
        <td><%= beginner.author %></td>
        <td><%= beginner.user&.email  %></td>
        <td><%= link_to 'Show', beginner %></td>
        <% if beginner.user == current_user %>
        <td><%= link_to 'Edit', edit_beginner_path(beginner) %></td>
        <td><%= link_to 'Destroy', beginner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beginner', new_beginner_path %>

app/views/beginners/new.html.erb
<h1>New Beginner</h1>

<%= render 'form', beginner: @beginner %>

<%= link_to 'Back', beginners_path %>

app/views/beginners/show.html.erb
<p id="notice"><%= notice %></p>
  <beginner_show :beginner="<%= @beginner.to_json %>"></beginner_show>
<div class="Beginner">

<p>
  <strong>Title:</strong>
  <%= @beginner.title %>
</p>

<p>
  <strong>Element:</strong>
  <%= @beginner.element %>
</p>

<p>
  <strong>Author:</strong>
  <%= @beginner.author %>
</p>

<%= link_to 'Edit', edit_beginner_path(@beginner) %> |
<%= link_to 'Back', beginners_path %>
</div>
</br>
<div class="comments">
  <table>
    <thead>
      <tr>
        <th>Text</th>
        <th>Author</th>
      </tr>
    </thead>


    <tbody>
      <% @beginner.comments.each do |comment| %>
        <tr>
          <td><%= comment.text %></td>
          <td><%= comment.author %></td>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>
</br>
<div class="new_comments">
  <%= render 'comments/form', comment: @new_comment %>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :beginner_id %>
    <%= form.text_field :beginner_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Author</th>
      <th>Beginners</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= comment.author %></td>
        <td><%= comment.beginner %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Beginners:</strong>
  <%= @comment.beginner %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beginners</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>

    <div class="container" data-behavior="vue">
      <%= yield %>

    </div>
  </body>
</html>